[project]
name = "backend"
version = "0.1.0"
description = "Backend API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "alembic",
    "psycopg2-binary",
    "asyncpg",
    "pydantic",
    "pydantic-settings",
    "boto3",
    "passlib[bcrypt]==1.7.4",
    "bcrypt==3.1.7",
    "python-jose[cryptography]",
    "python-multipart",
    "pytz",
    "gunicorn",
    "slowapi"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "httpx",
    "pytest-asyncio",
    "ruff",
    "mypy"
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
strict = false
