/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login For Access Token
         * @description Motor de Login B2B (Segurança Camada Zero).
         *     Retorna o Payload JWT estrito para o Next.js colocar em LocalStorage/Cookies.
         */
        post: operations["login_for_access_token_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/upload-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload Intent
         * @description Início do ciclo: status PENDING_UPLOAD. O upload é direto pro S3 (Bypass),
         *     mantendo o servidor leve e performático.
         */
        post: operations["create_upload_intent_posts_upload_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Post
         * @description Segurança Stateless via JWT: apenas usuários autenticados criam posts
         */
        post: operations["create_post_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Post
         * @description Inversão de Dependência: o controlador delega a lógica para o Caso de Uso.
         */
        get: operations["get_post_posts__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Visual Pin Comment
         * @description Validação Sniper: o Pydantic garante x/y entre 0 e 100.
         *     Se falhar, o Swagger já expõe o erro 400 automaticamente.
         */
        post: operations["add_visual_pin_comment_posts__post_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Rota de telemetria crua para o Load Balancer e Docker Healthcheck
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_for_access_token_auth_login_post */
        Body_login_for_access_token_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CommentCreateRequest */
        CommentCreateRequest: {
            /**
             * User Id
             * Format: uuid
             * @description UUID do colaborador que está criando o Pin
             */
            user_id: string;
            /**
             * Content
             * @description Texto do feedback visual
             * @example Ajustar saturação nesta área
             */
            content: string;
            /**
             * Coord X
             * @description Posição X em %
             * @example 45.5
             */
            coord_x: number;
            /**
             * Coord Y
             * @description Posição Y em %
             * @example 78.2
             */
            coord_y: number;
        };
        /** CommentResponse */
        CommentResponse: {
            /**
             * Id
             * Format: uuid
             * @description ID Identificador do Pin
             */
            id: string;
            /**
             * Post Id
             * Format: uuid
             * @description Post vinculado
             */
            post_id: string;
            /**
             * User Id
             * Format: uuid
             * @description Autor do feedback
             */
            user_id: string;
            /**
             * Content
             * @description Texto do comentário
             */
            content: string;
            /**
             * Coord X
             * @description Coordenada X em %
             */
            coord_x: number;
            /**
             * Coord Y
             * @description Coordenada Y em %
             */
            coord_y: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PostCreateRequest */
        PostCreateRequest: {
            /**
             * Calendar Id
             * Format: uuid
             * @description ID B2B do calendário associado ao Cliente/Agência
             */
            calendar_id: string;
            /**
             * Media Url
             * @description Link Pre-signed S3 da mídia blindando a RAM do servidor
             */
            media_url: string;
        };
        /**
         * PostDetailResponse
         * @description Resposta completa com todos os feedbacks visuais (Eager Loading)
         */
        PostDetailResponse: {
            /**
             * Id
             * Format: uuid
             * @description Identificador universal rígido do Post Kanban
             */
            id: string;
            /**
             * Calendar Id
             * Format: uuid
             * @description UUID do calendário proprietário
             */
            calendar_id: string;
            /**
             * Media Url
             * @description URL de acesso à mídia no S3
             * @example https://bucket.s3.amazonaws.com/uuid.mp4
             */
            media_url: string;
            /** @description Motor de estado restrito (CRIADO, APROVADO, etc) */
            status: components["schemas"]["PostStatus"];
            /**
             * Comments
             * @description Lista de feedbacks (Pins) do vídeo
             * @default []
             */
            comments: components["schemas"]["CommentResponse"][];
        };
        /** PostResponse */
        PostResponse: {
            /**
             * Id
             * Format: uuid
             * @description Identificador universal rígido do Post Kanban
             */
            id: string;
            /**
             * Calendar Id
             * Format: uuid
             * @description UUID do calendário proprietário
             */
            calendar_id: string;
            /**
             * Media Url
             * @description URL de acesso à mídia no S3
             * @example https://bucket.s3.amazonaws.com/uuid.mp4
             */
            media_url: string;
            /** @description Motor de estado restrito (CRIADO, APROVADO, etc) */
            status: components["schemas"]["PostStatus"];
        };
        /**
         * PostStatus
         * @description O status controla o ciclo de vida no Kanban.
         *     O sistema é uma máquina de estados que protege o fluxo do post.
         * @enum {string}
         */
        PostStatus: "PENDING_UPLOAD" | "CRIADO" | "AGUARDANDO_APROVACAO" | "APROVADO" | "REJEITADO";
        /** UploadIntentRequest */
        UploadIntentRequest: {
            /**
             * Filename
             * @description Nome original do arquivo
             * @example campanha_outono.mp4
             */
            filename: string;
            /**
             * Content Type
             * @description MIME type do arquivo
             * @example video/mp4
             */
            content_type: string;
            /**
             * Calendar Id
             * Format: uuid
             * @description ID do calendário para vincular o novo Post
             */
            calendar_id: string;
        };
        /** UploadIntentResponse */
        UploadIntentResponse: {
            /**
             * Upload Url
             * @description URL assinada para upload direto ao S3
             */
            upload_url: string;
            /**
             * File Key
             * @description Chave única gerada para o arquivo no storage
             */
            file_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_for_access_token_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_intent_posts_upload_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetailResponse"];
                };
            };
            /** @description Post não localizado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_visual_pin_comment_posts__post_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Coordenadas inválidas */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post não localizado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
